### ISSUE TITLE
CAD

### ISSUE THREAD

**Issue by dtdionne** [JaredC01/Galileo2#24]
Where's CAD?

You can't use GNU and not release CAD.  Psudocode (STL's) AINT source code (CAD).  Release the CAD or change your license.

**Comment by JaredC01** [comment]
Tell me you haven't read the project page without telling me you haven't read the project page.

GNU says CAD must be available, not that it has to be posted with the project. At this point, we are nearly done with beta as well, so CAD will be released at completion of beta to the project page.

Closing, and in the future if you have a question regarding the project, post that rather than an aggressive post telling me to change the license type.

- Jared
